### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by poonkundransrinivasan** [INFO523-S24/project-01-TAAAG-team#2]
The following is the peer review of the project proposal by Stats N Facts The team members that participated in this review are 

- Nandhini Anne - @NandhiniAnne
- Sunday Usman - @sundayusman
- H M Abdul Fattah - @hmfattah
- Shreemithra Naveen - @shreemithran
- Srinivasan Poonkundran - @kANNISTER

**- Describe the goal of the project.**
This project offers a basis for more in-depth research into the variables impacting the English Premier League season of 2021–2022.
The goal of question 1 is to perform an analysis and to check if there is any connection between the in-game metrics (fouls, shots, and cards received) and outcomes of soccer matches. In question 2, they are focusing on a hypothetical scenario where how it may affect the game or leaderboard if the games are done at half time. This project offers a basis for more in-depth research into the variables impacting the English Premier League season of 2021–2022.

**- Describe the data used or collected.**
The data used in the project consists of match-day statistics from the 2021–2022 English Premier League season. It includes information such as match dates, home and away teams, goals scored, fouls committed, and cards received.

**- Describe how the research question will be answered, e.g. what approaches/methods will be used.**
Regression techniques, including logistic regression or decision trees, and predictive models these approaches and methods will be applied to the provided dataset to address the research questions

**- Is there anything that is unclear from the proposal?**
The question 1 does look good and is clear on what the outcomes will be.
However, in our opinion regarding the question 2, variability in match outcome cannot be accurately assesed without considering the entirety of play. Although, we understand that this question is trying to address a hypothetical scenario, we are not sure if this is logical/worth exploring. 

**- Provide constructive feedback on how the team might be able to improve their project.**
In the question 2, we would recommend to modify/rephrase the question so that it works on more of a practical scenario rather than a hypothetical one. For example focusing on analysing combacks in matches might be more impactful. 

**- What aspect of this project are you most interested in and would like to see highlighted in the presentation?**
The dataset looks super interesting and contains a lot of information. We really liked the application and broader perspective that the question 1 covers and we would love to see that being highlighted.  

**- Provide constructive feedback on any issues with file and/or code organization.**
Only concern we have about this proposal is, modify/update question 2 to analyze something more practical. 

- (Optional) Any further comments or feedback?

**Comment by ayeshakhatunsujana** [comment]
We truly value your meticulous and thorough evaluation of our project proposal. We appreciate your suggestions on how to better explain our data and code, as well as your ideas on how to clarify our procedures—especially in relation to our second study question. We will try to close any knowledge gaps and offer more specifics about our computational techniques. We are excited to look into this more and appreciate your interest in the accuracy of our forecasting model. We'll also reduce our code to avoid duplication and unnecessary package calls. We have already modified the second query. We want to thank you again for your supportive remarks and insightful critiques, which are much appreciated as we carry on with this project.

Best Regards
Team TAAAG
