### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by remisublette** [INFO523-S24/project-01-TAAAG-team#4]
The following is the peer review of the Presentation proposal by [name of team completing peer review]. The team members who participated in this review are 

Omid Zandi - [@zandi-omid](https://github.com/zandi-omid)
Praveen Kumar Pappala - [@Praveen-Kumar-Pappala](https://github.com/Praveen-Kumar-Pappala)
Priom Mahmud - [@Priom1996](https://github.com/Priom1996)
Mohammad Farmani - [@mfarmani95](https://github.com/mfarmani95)
Remi Hendershott - [@remisublette](https://github.com/remisublette)
Deema Albluwi -[@Dee-koudz](https://github.com/Dee-koudz)

- Content: Is the research question well designed and is the data being used relevant to the research question?
The research inquiry was meticulously formulated, and the employed dataset was effectively utilized and scrutinized to address inquiries concerning the predictive capabilities of end-game metrics and halftime scores on final game outcomes.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
Indeed, the team demonstrated proficiency in visual representation through the utilization of informative visuals such as confusion matrices and feature correlation heat maps. They presented a diverse array of visualization techniques, accompanied by articulate explanations from the speakers, thereby enhancing the audience's comprehension of their plots and their significance.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
The approach taken to analyze sports data was intriguing, showcasing a dedication of time and effort to the project. Through comprehensive analysis of full-time game data and predictive modeling of halftime scores, the team conscientiously addressed potential limitations, demonstrating a thorough understanding of the dataset and research objectives.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
Yes, their slides were great! They had a funny meme at the end, the slides were meticulously crafted, featuring a clean and well-organized layout. Each plot was thoughtfully presented, ensuring clarity and avoiding clutter, with concise and effective labeling. In summary, an excellent execution of their presentation slides.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
 They did well overall as a team. There was some slight delay in reading their points periodically, but with it being virtual, it is understandable. Their team seemed to be unified, and it seemed everyone had a good grip on the presentation's points and participated equally.

**Comment by ayeshakhatunsujana** [comment]
Thank you for your feedback!
