### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by poonkundransrinivasan** [INFO523-S24/project-01-TAAAG-team#5]
The following is the peer review of the Presentation proposal by [name of team completing peer review]. The team members that participated in this review are 

Nandhini Anne - @NandhiniAnne
Sunday Usman - @sundayusman
H M Abdul Fattah - @hmfattah
Shreemithra Naveen - @shreemithran
Srinivasan Poonkundran - @kANNISTER

**Is the research question well designed and is the data being used relevant to the research question?**
The research questions were relevant and extremely well designed 

**Did the team use appropriate visualizations and did they interpret them accurately?**
Regardless of having such a tricky dataset, visualizations of this team was super cool, intriguing and was on point. The insights were also well explained.

**Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?**
Yes, the whole project was carefully thought, limitations were also considered.

**Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?**
Although some slides had more text than expected, sometimes it becomes necessary to do so and this might have been the case what this team faced. But the organization of the slides was perfect, Labels and legends of the plots were short and crisp.

**Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?**
Regardless of the presentation going a bit longer than expected, the team did a fantastic job of explaining each and every aspect of their project. And yes, every member did get a chance to say something meaningful about the project.

**Comment by ayeshakhatunsujana** [comment]
Thank you for your feedback!
